### ISSUE TITLE
Sessions can not be created 

### ISSUE THREAD

**Issue by goncer** [Xotabu4/selenoid-github-action#5]
Hi,
First! thanks for this action! looks awesome, but I am running into an issue that I don't know how to solve it. 
It seems that when trying to create the session it fails badly ;(

```
FAIL test/ui/ui-get.tokens.test.ts (38.307 s)
  UI tests - Get Tokens from Faucet
    ✕ As a User I can get test tokens from the faucet (5617 ms)

  ● UI tests - Get Tokens from Faucet › As a User I can get test tokens from the faucet

    WebDriverError: New session attempts retry count exceeded
```
It seems that is running and so on, but does not work :S
https://github.com/mangata-finance/mangata-e2e/runs/3181379335?check_suite_focus=true
Any clue?
Thanks!
Here the gitflow :)

https://github.com/mangata-finance/mangata-e2e/pull/26/files#diff-f49ef8660b7beda3e4f02dfa0c6895295a5873f841bbcb41a9407dc33402e7df

**Comment by goncer** [comment]
The issue was about capabilities, 
```
let caps: Capabilities = new Capabilities();
      caps = Capabilities.chrome();
      caps.set("version", "91.0");
      caps.set("selenoid:options", {enableVNC: true, enableVideo: true })
      
      driver = new Builder()
          .forBrowser('chrome')
          .setChromeOptions(options)
          .withCapabilities(caps)
          .build();
```
Also, dont knwo why, it does not work with chrome92. have to run with arguments,

```
      - name: Start Selenoid Server
        uses: Xotabu4/selenoid-github-action@v2
        with:
          selenoid-start-arguments: |
            --args "-timeout 60s" --browsers 'chrome' --last-versions 2 
```
