### ISSUE TITLE
Multiple executions

### ISSUE THREAD

**Issue by inluxc** [Xotabu4/selenoid-github-action#6]
I'm using this job, but for some reason, I cant get it to work, what I'm missing here?

```
  run:
    strategy:
      matrix:
        browsers: [chrome,firefox,edge]
      max-parallel: 1
    runs-on: ubuntu-latest
    needs:
      - build
    name: ${{ matrix.browsers }}
    steps:
      - name: Start selenoid
        uses: Xotabu4/selenoid-github-action@v2
        with:
          selenoid-start-arguments: |
            --args "-b '${{ matrix.browsers }}'"
```

**Comment by inluxc** [comment]
Forget it i found my mistake :(

```
  run:
    strategy:
      matrix:
        browsers: [chrome,firefox,edge]
      max-parallel: 1
    runs-on: ubuntu-latest
    needs:
      - build
    name: ${{ matrix.browsers }}
    steps:
      - name: Start selenoid
        uses: Xotabu4/selenoid-github-action@v2
        with:
          selenoid-start-arguments: |
            --browsers '${{ matrix.browsers }}' --last-versions 1
      - name: is selenoid started?
        run: curl http://localhost:4444/status

```
